sudo: false

language: node_js
node_js:
- '12'

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
  - npm cache clean --force

install:
  - npm install -g codecov

cache:
  directories:
  - $HOME/.npm
  - node_modules

script:
- npm install --no-optional
- npm run test
- codecov
- npm run build
- docker build -t crviz -f Dockerfile .
- docker build -t crviz-gh -f Dockerfile.gh .